# Generated by Django 5.0.4 on 2024-10-26 19:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donate',
            fields=[
                ('uuids', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bankName', models.CharField(blank=True, max_length=50, null=True)),
                ('accountNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('AccountName', models.CharField(blank=True, max_length=50, null=True)),
                ('imagex1', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='homepage',
            fields=[
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('uuids', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('header', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, max_length=50, null=True)),
                ('imagex', models.TextField(blank=True, max_length=50, null=True)),
                ('imagex1', models.TextField(blank=True, max_length=50, null=True)),
                ('imagex2', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('uuids', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('view', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('uuids', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('view', models.IntegerField(blank=True, null=True)),
                ('header', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, max_length=50, null=True)),
                ('imagex', models.TextField(blank=True, max_length=50, null=True)),
                ('imagex1', models.TextField(blank=True, max_length=50, null=True)),
                ('imagex2', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='siteedit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('domain', models.CharField(blank=True, default=models.CharField(blank=True, max_length=50, null=True), max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('dis', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('image1', models.TextField(blank=True, null=True)),
                ('idx', models.IntegerField(default=1)),
            ],
        ),
    ]
