# Generated by Django 5.0.4 on 2024-10-31 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_job_body_alter_report_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='report',
            new_name='reportx',
        ),
    ]
