# Generated by Django 5.0.4 on 2024-10-31 08:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_report_reportx'),
    ]

    operations = [
        migrations.CreateModel(
            name='teams',
            fields=[
                ('uuids', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('position', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
