# Generated by Django 5.0.4 on 2024-10-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_job_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='idx',
        ),
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
        migrations.AddField(
            model_name='job',
            name='closedate',
            field=models.DateField(blank=True, max_length=500, null=True),
        ),
    ]
