# Generated by Django 5.0.4 on 2024-10-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_job_idx_remove_job_image_job_closedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='TYPE',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
