# Generated by Django 5.0.4 on 2024-10-31 17:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankdetail',
            fields=[
                ('uuids', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('bankdetailnumber', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, max_length=500, null=True)),
                ('additional', models.DateField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
