# Generated by Django 5.0.4 on 2024-10-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_cdate_press_cdatex'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='header',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
