# Generated by Django 5.0.4 on 2024-10-31 19:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_press_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='publications',
            fields=[
                ('uuids', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('header', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('Author', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
