# Generated by Django 5.0.4 on 2024-10-31 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_publications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='publications',
            new_name='publicationsx',
        ),
    ]
