# Generated by Django 5.0.4 on 2024-11-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_projectx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectx',
            old_name='TYPE',
            new_name='header',
        ),
    ]
