# Generated by Django 5.0.4 on 2024-11-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_aboutuse_building_alter_aboutuse_buildingimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuse',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
