# Generated by Django 5.0.4 on 2024-11-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_aboutuse_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteedit',
            name='headoffice2',
        ),
    ]
