# Generated by Django 5.0.4 on 2024-11-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_siteedit_headoffice2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='idx',
        ),
    ]
