# Generated by Django 5.0.4 on 2024-11-01 11:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_contactus_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='donatetor',
            fields=[
                ('uuids', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
