# Generated by Django 5.0.4 on 2024-11-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_job_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='closedate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
