# Generated by Django 5.0.4 on 2024-11-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_job_body_alter_job_closedate_alter_job_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='view',
        ),
        migrations.RemoveField(
            model_name='news',
            name='view',
        ),
        migrations.RemoveField(
            model_name='press',
            name='view',
        ),
    ]
