# Generated by Django 5.0.4 on 2024-11-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_job_closedate_alter_job_date_alter_news_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Status',
            field=models.CharField(blank=True, choices=[('Position Closed', 'Position Closed'), ('Position Closed', 'Position Closed')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='TYPE',
            field=models.CharField(blank=True, choices=[('part time', 'Parttime'), ('full-time', 'Fulltime')], max_length=500, null=True),
        ),
    ]
