# Generated by Django 5.0.4 on 2024-11-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_job_status_alter_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Status',
            field=models.CharField(blank=True, choices=[('Position open', 'Position open'), ('Position Closed', 'Position Closed')], max_length=500, null=True),
        ),
    ]
