# Generated by Django 5.0.4 on 2024-11-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_reportx_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectx',
            name='Status',
            field=models.CharField(blank=True, choices=[('project open', 'project open'), ('project Closed', 'project Closed')], max_length=500, null=True),
        ),
    ]
