# Generated by Django 3.2.25 on 2024-12-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_aboutuse_association_alter_aboutuse_ourmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='expertteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('idx', models.IntegerField(default=1)),
            ],
        ),
    ]
