# Generated by Django 3.2.25 on 2024-12-13 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_expertteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='expertteam',
        ),
    ]
